### ISSUE TITLE
Tournament start button doesn't change dynamically

### ISSUE THREAD

**Issue by ionorb** [maofalt/Transcendence#290]
When I click on the "start" button it doesn't update to "play". I have to refresh the page.

This is the button I am referring to:
![Screenshot from 2024-04-12 22-55-41](https://github.com/maofalt/Transcendence/assets/71927888/54bda056-8f63-42bd-8710-b43cdb63edbf)

This is what it should change to:
![Screenshot from 2024-04-12 23-01-18](https://github.com/maofalt/Transcendence/assets/71927888/816e3031-9e68-4f23-9c4c-56525efe194b)

**Comment by ionorb** [comment]
Oh... wait it does work. Idk why it wasn't working before...

**Comment by maofalt** [comment]
@ionorb  You are actually right! When backend is under some load or it a little bit slow I the play button doesnt appear, since the response is not ok. 
i was waiting 100 ms rather than waiting the other response since chaining events is a little bit more difficult but i will implement in order  to solve the async calls.
